# =============================================================================
# Generate figures and tables from the Briscola simulation output.
# =============================================================================
# Inputs:
#   briscola_analysis_extended.csv  (game-level, produced by
#                                    analysis_briscola_hypothesis.R)
#   bin/Debug/net8.0/briscola_simulazione.csv (trick-level, 2.7 GB)
#
# Outputs (into papers/briscola/):
#   fig_breakeven.pdf       Win-rate vs briscola imbalance per matchup
#   tab_winrates.tex        Wilson-CI table of head-to-head G1 win rates
#   tab_logit.tex           Logistic regression odds-ratio table
#   tab_briscola_use.tex    Counter-diagnostic: briscola-use efficiency
#
# Usage:  Rscript make_figures.R
# =============================================================================

suppressPackageStartupMessages({
  library(data.table)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(binom)
  library(broom)
})

out_dir <- normalizePath("../papers/briscola")
if (!dir.exists(out_dir)) stop("Output dir missing: ", out_dir)
cat("Output directory:", out_dir, "\n")

# ---------------------------------------------------------------------------
# Load pre-aggregated game-level data
# ---------------------------------------------------------------------------
games <- fread("briscola_analysis_extended.csv")
setnames(games, tolower(names(games)))
cat("Games:", nrow(games), "\n")

# ---------------------------------------------------------------------------
# Table 1: head-to-head win rates with Wilson CIs
# ---------------------------------------------------------------------------
win_rates <- games[winner != "Pareggio",
  .(n = .N,
    wins_g1 = sum(winner == "G1"),
    rate = mean(winner == "G1")),
  by = .(strategyg1, strategyg2)]
ci <- binom.confint(win_rates$wins_g1, win_rates$n, methods = "wilson")
win_rates[, `:=`(lower = ci$lower, upper = ci$upper)]
win_rates <- win_rates[order(strategyg1, strategyg2)]
print(win_rates)

# Emit a 3x3 LaTeX fragment: strategies ordered Greedy, Hoarder, Counter.
strats <- c("Greedy", "Hoarder", "Counter")
macros <- c(Greedy = "\\stratG", Hoarder = "\\stratH", Counter = "\\stratC")
cell <- function(r) sprintf("$%.3f$\\;\\footnotesize{[%.3f, %.3f]}",
                            r$rate, r$lower, r$upper)

tex <- c(
  "% Auto-generated by src/make_figures.R -- do not edit by hand.",
  "\\begin{table}[t]",
  "  \\centering",
  "  \\caption{Head-to-head win rate of $G_1$ and Wilson 95\\% confidence interval. ",
  "  Rows index $G_1$'s policy, columns index $G_2$'s policy. ",
  "  Each cell is estimated from $\\approx 1.08\\cdot 10^5$ non-tied games.}",
  "  \\label{tab:winrates}",
  "  \\begin{tabular}{lccc}",
  "    \\toprule",
  "    $G_1$ $\\backslash$ $G_2$ & \\stratG & \\stratH & \\stratC \\\\",
  "    \\midrule"
)
for (s1 in strats) {
  row_cells <- sapply(strats, function(s2) {
    r <- win_rates[strategyg1 == s1 & strategyg2 == s2]
    cell(r)
  })
  tex <- c(tex, sprintf("    %s & %s \\\\", macros[s1], paste(row_cells, collapse = " & ")))
}
tex <- c(tex, "    \\bottomrule", "  \\end{tabular}", "\\end{table}")
writeLines(tex, file.path(out_dir, "tab_winrates.tex"))
cat("Wrote:", file.path(out_dir, "tab_winrates.tex"), "\n")

# ---------------------------------------------------------------------------
# Table 2: logistic regression of P(G1 wins)
# ---------------------------------------------------------------------------
glm_data <- games[winner != "Pareggio"][, `:=`(
  g1_wins = as.integer(winner == "G1"),
  strat_g1 = factor(strategyg1, levels = strats),
  strat_g2 = factor(strategyg2, levels = strats),
  briscoladiff = briscoletotalig1 - briscoletotalig2
)]
fit <- glm(g1_wins ~ strat_g1 + strat_g2 + briscoladiff,
           data = glm_data, family = binomial())
or_tbl <- tidy(fit, exponentiate = TRUE, conf.int = TRUE, conf.level = 0.95)
print(or_tbl)

term_label <- c(
  "(Intercept)"    = "Intercept",
  "strat_g1Hoarder" = "$G_1 = \\stratH$",
  "strat_g1Counter" = "$G_1 = \\stratC$",
  "strat_g2Hoarder" = "$G_2 = \\stratH$",
  "strat_g2Counter" = "$G_2 = \\stratC$",
  "briscoladiff"    = "$\\Delta_{\\text{briscola}}$ (per $+1$)"
)
or_tbl$label <- term_label[or_tbl$term]
fmt_p <- function(p) {
  fmt_sci <- function(q) {
    s <- sprintf("%.1e", q)
    parts <- strsplit(s, "e", fixed = TRUE)[[1]]
    sprintf("$%s\\times 10^{%d}$", parts[1], as.integer(parts[2]))
  }
  ifelse(p < 1e-300, "$<10^{-300}$",
  ifelse(p < 1e-4,   vapply(p, fmt_sci, character(1)),
                     sprintf("%.4f", p)))
}
tex <- c(
  "% Auto-generated by src/make_figures.R",
  "\\begin{table}[t]",
  "  \\centering",
  "  \\caption{Logistic regression of $\\Pr(G_1~\\text{wins})$ on the two policies and the ",
  "  briscola-count imbalance $\\Delta_{\\text{briscola}}=B_{G_1}-B_{G_2}$. ",
  "  Odds ratios with 95\\% Wald confidence intervals. Reference category: $\\stratG$. ",
  sprintf("  Fitted on $N = %s$ non-tied games.}",
          formatC(nrow(glm_data), big.mark = "\\,", format = "d")),
  "  \\label{tab:logit}",
  "  \\begin{tabular}{lrrc}",
  "    \\toprule",
  "    Term & OR & 95\\% CI & $p$-value \\\\",
  "    \\midrule"
)
for (i in seq_len(nrow(or_tbl))) {
  r <- or_tbl[i, ]
  tex <- c(tex, sprintf("    %s & $%.3f$ & $[%.3f, %.3f]$ & %s \\\\",
                        r$label, r$estimate, r$conf.low, r$conf.high, fmt_p(r$p.value)))
}
tex <- c(tex, "    \\bottomrule", "  \\end{tabular}", "\\end{table}")
writeLines(tex, file.path(out_dir, "tab_logit.tex"))
cat("Wrote:", file.path(out_dir, "tab_logit.tex"), "\n")

# ---------------------------------------------------------------------------
# Figure: break-even curves (P(G1 wins) vs briscola imbalance per matchup)
# ---------------------------------------------------------------------------
breakeven <- games[winner != "Pareggio", {
  bdiff <- briscoletotalig1 - briscoletotalig2
  .SD[, .(n = .N, w = sum(winner == "G1")), by = .(bdiff)]
}, by = .(strategyg1, strategyg2)]
breakeven <- breakeven[n >= 50]  # hide tails with too few games
ci2 <- binom.confint(breakeven$w, breakeven$n, methods = "wilson")
breakeven[, `:=`(rate = w/n, lower = ci2$lower, upper = ci2$upper)]
breakeven[, strategyg1 := factor(strategyg1, levels = strats)]
breakeven[, strategyg2 := factor(strategyg2, levels = strats)]

p <- ggplot(breakeven, aes(x = bdiff, y = rate)) +
  geom_hline(yintercept = 0.5, linetype = "dashed", colour = "grey60") +
  geom_vline(xintercept = 0,   linetype = "dashed", colour = "grey60") +
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = "grey80", alpha = 0.6) +
  geom_line(linewidth = 0.6) +
  geom_point(size = 1.1) +
  facet_grid(strategyg1 ~ strategyg2,
             labeller = label_bquote(rows = G[1]*":"~.(as.character(strategyg1)),
                                     cols = G[2]*":"~.(as.character(strategyg2)))) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.25, 0.5, 0.75, 1)) +
  scale_x_continuous(breaks = seq(-10, 10, 2)) +
  labs(x = expression(Delta[briscola] == B[G[1]] - B[G[2]]),
       y = expression(widehat(P)(G[1]~"wins"))) +
  theme_bw(base_size = 10) +
  theme(panel.grid.minor = element_blank(),
        strip.background = element_rect(fill = "grey92", colour = NA))

ggsave(file.path(out_dir, "fig_breakeven.pdf"), p, width = 7, height = 6.3)
cat("Wrote:", file.path(out_dir, "fig_breakeven.pdf"), "\n")

# ---------------------------------------------------------------------------
# Counter diagnostic: briscola-use efficiency from the raw trick-level log
# ---------------------------------------------------------------------------
# We select only the columns we need: strategy pair, the briscola suit, the two
# played cards, the per-trick points, and who won the trick.
csv_raw <- "bin/Debug/net8.0/briscola_simulazione.csv"
cat("Reading trick-level CSV:", csv_raw, "\n")
tricks <- fread(
  csv_raw, sep = ";",
  select = c("StrategyG1","StrategyG2","SemeBriscola",
             "CartaG1","CartaG2","VincitoreMano","PuntiMano"),
  showProgress = TRUE
)
cat("Tricks loaded:", nrow(tricks), "\n")

# Parse "Carta { Seme = X, Rango = Y, Punti = Z }" into three columns per card.
parse_carta <- function(col) {
  mat <- stringi::stri_match_first_regex(
    col, "Seme = ([A-Za-z]+), Rango = (\\d+), Punti = (\\d+)")
  list(seme = mat[, 2], rango = as.integer(mat[, 3]),
       punti = as.integer(mat[, 4]))
}
g1 <- parse_carta(tricks$CartaG1)
g2 <- parse_carta(tricks$CartaG2)
tricks[, `:=`(seme_g1 = g1$seme, punti_g1 = g1$punti, rango_g1 = g1$rango,
              seme_g2 = g2$seme, punti_g2 = g2$punti, rango_g2 = g2$rango)]
tricks[, `:=`(played_briscola_g1 = seme_g1 == SemeBriscola,
              played_briscola_g2 = seme_g2 == SemeBriscola)]

# Per-policy diagnostic: when a policy plays one of its own briscole, how many
# trick points does it collect (per trick) and how often is it played "empty"
# (i.e. opponent card is worth 0)?
agg <- rbind(
  tricks[played_briscola_g1 == TRUE,
         .(role = "G1", strategy = StrategyG1,
           opp_strategy = StrategyG2,
           won = as.integer(VincitoreMano) == 1L,
           trick_pts = PuntiMano,
           opp_was_zero = punti_g2 == 0)],
  tricks[played_briscola_g2 == TRUE,
         .(role = "G2", strategy = StrategyG2,
           opp_strategy = StrategyG1,
           won = as.integer(VincitoreMano) == 2L,
           trick_pts = PuntiMano,
           opp_was_zero = punti_g1 == 0)]
)

diag_tbl <- agg[, .(
  n_played       = .N,
  win_rate       = mean(won),
  mean_pts_when_won = sum(trick_pts * won) / sum(won),
  wasted_frac    = mean(opp_was_zero)
), by = .(strategy)][order(match(strategy, strats))]
print(diag_tbl)

tex <- c(
  "% Auto-generated by src/make_figures.R",
  "\\begin{table}[t]",
  "  \\centering",
  "  \\caption{Briscola-use profile per policy, pooled across all matchups and ",
  "  both player roles. Columns: (i) number of tricks in which the policy ",
  "  played a briscola; (ii) fraction of those tricks won; (iii) average ",
  "  points captured per winning briscola trick; (iv) fraction of briscole ",
  "  played against a zero-point opposing card --- a proxy for `wasted' trumps.}",
  "  \\label{tab:briscola_use}",
  "  \\begin{tabular}{lrrrr}",
  "    \\toprule",
  "    Policy & $n_{\\text{played}}$ & Win rate & Mean pts.\\ per win & Wasted fraction \\\\",
  "    \\midrule"
)
for (i in seq_len(nrow(diag_tbl))) {
  r <- diag_tbl[i, ]
  tex <- c(tex, sprintf("    %s & $%s$ & $%.3f$ & $%.2f$ & $%.3f$ \\\\",
                        macros[r$strategy],
                        formatC(r$n_played, big.mark = "\\,", format = "d"),
                        r$win_rate, r$mean_pts_when_won, r$wasted_frac))
}
tex <- c(tex, "    \\bottomrule", "  \\end{tabular}", "\\end{table}")
writeLines(tex, file.path(out_dir, "tab_briscola_use.tex"))
cat("Wrote:", file.path(out_dir, "tab_briscola_use.tex"), "\n")

cat("\nAll outputs generated.\n")
